AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-search-products

  Sample SAM Template for lambda-search-products

Globals:
  Function:
    Timeout: 10

Resources:
  SearchProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: search/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Environment:
        Variables:
          DATABASE_URL: postgresql://admin:DMcOMJ8zJpXCRSkMofm9O6MFVAC36MfY@dpg-cqo1q4jv2p9s73aj35eg-a.virginia-postgres.render.com/db_midas_vvpk?ssl=true
      Events:
        Products:
          Type: Api
          Properties:
            Path: /products
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
